import {
  WhatsAppIcon, InstagramIcon, GlobeIcon, MailIcon,
  UserIcon, BoltIcon, CartIcon, WarningIcon,
  ChatIcon, CreditCardProcessIcon, TruckIcon, LinkIcon,
} from '@/components/icons';
import type { ActivityItem, ActivityStatus, AttentionItem, AutomationCard, ConversationPreview, MetricItem } from './types';

export const liveActivity: ActivityItem[] = [
  {
    id: 1,
    icon: <ChatIcon />,
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    text: 'AI replied to Adebayo O. about order status',
    status: 'success',
    time: '30s ago',
  },
  {
    id: 2,
    icon: <CreditCardProcessIcon />,
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    text: 'Payment of \u20A624,500 processed for order #ORD-2851',
    status: 'success',
    time: '1m ago',
  },
  {
    id: 3,
    icon: <ChatIcon />,
    channelIcon: <InstagramIcon />,
    channel: 'Instagram',
    text: 'New message from Funke A. \u2014 "I want to return this item"',
    status: 'info',
    time: '2m ago',
  },
  {
    id: 4,
    icon: <UserIcon />,
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    text: 'Ngozi I. escalated to human agent \u2014 payment complaint',
    status: 'escalated',
    time: '4m ago',
  },
  {
    id: 5,
    icon: <CartIcon />,
    channelIcon: <GlobeIcon />,
    channel: 'Web Chat',
    text: 'New order #ORD-2852 created \u2014 \u20A618,000 (3 items)',
    status: 'success',
    time: '6m ago',
  },
  {
    id: 6,
    icon: <TruckIcon />,
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    text: 'Delivery #DEL-1923 marked completed \u2014 notified customer',
    status: 'success',
    time: '8m ago',
  },
  {
    id: 7,
    icon: <BoltIcon />,
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    text: 'Automation "Abandoned Cart" recovered \u20A612,400 sale',
    status: 'success',
    time: '12m ago',
  },
  {
    id: 8,
    icon: <WarningIcon />,
    channelIcon: <BoltIcon />,
    channel: 'System',
    text: 'Automation "Lead Qualifier" error rate exceeded 5%',
    status: 'failed',
    time: '15m ago',
  },
  {
    id: 9,
    icon: <ChatIcon />,
    channelIcon: <MailIcon />,
    channel: 'Email',
    text: 'AI sent follow-up email to Kemi D. about pending invoice',
    status: 'success',
    time: '18m ago',
  },
  {
    id: 10,
    icon: <CreditCardProcessIcon />,
    channelIcon: <InstagramIcon />,
    channel: 'Instagram',
    text: 'Payment link sent to Tolu M. \u2014 \u20A68,500',
    status: 'info',
    time: '22m ago',
  },
];

export const attentionItems: AttentionItem[] = [
  {
    icon: <UserIcon />,
    color: 'orange',
    label: 'Awaiting human reply',
    count: 3,
    href: '/conversations',
    urgent: true,
  },
  {
    icon: <WarningIcon />,
    color: 'red',
    label: 'Failed automation runs',
    count: 1,
    href: '/automations',
    urgent: true,
  },
  {
    icon: <LinkIcon />,
    color: 'gray',
    label: 'Disconnected channels',
    count: 1,
    href: '/channels',
    urgent: false,
  },
  {
    icon: <CreditCardProcessIcon />,
    color: 'red',
    label: 'Payment errors',
    count: 0,
    href: '/billing',
    urgent: false,
  },
];

export const metrics: MetricItem[] = [
  {
    label: 'Conversations Today',
    value: '142',
    sub: '38 open',
  },
  {
    label: 'AI Resolution Rate',
    value: '87%',
    sub: 'without human',
  },
  {
    label: 'Active Automations',
    value: '24',
    sub: '3 new this week',
  },
  {
    label: 'Revenue Processed',
    value: '\u20A62.1M',
    sub: 'today',
  },
];

export const automations: AutomationCard[] = [
  {
    name: 'Order Confirmation',
    status: 'live',
    icon: <CartIcon />,
    category: 'Commerce',
    runsToday: '234',
    successRate: '99.1%',
    lastRun: '2m ago',
  },
  {
    name: 'Abandoned Cart Recovery',
    status: 'live',
    icon: <BoltIcon />,
    category: 'Recovery',
    runsToday: '89',
    successRate: '97.8%',
    lastRun: '8m ago',
  },
  {
    name: 'Support Ticket Router',
    status: 'paused',
    icon: <ChatIcon />,
    category: 'Support',
    runsToday: '0',
    successRate: '95.2%',
    lastRun: '1h ago',
  },
  {
    name: 'Delivery Notification',
    status: 'live',
    icon: <TruckIcon />,
    category: 'Logistics',
    runsToday: '112',
    successRate: '99.6%',
    lastRun: '5m ago',
  },
  {
    name: 'Lead Qualifier',
    status: 'error',
    icon: <WarningIcon />,
    category: 'Sales',
    runsToday: '45',
    successRate: '91.3%',
    lastRun: '15m ago',
  },
  {
    name: 'Payment Reminder',
    status: 'live',
    icon: <CreditCardProcessIcon />,
    category: 'Billing',
    runsToday: '67',
    successRate: '98.4%',
    lastRun: '10m ago',
  },
];

export const conversations: ConversationPreview[] = [
  {
    name: 'Adebayo O.',
    initials: 'AO',
    msg: 'When will my order arrive? I placed it 3 days ago',
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    time: '2m ago',
    type: 'ai',
    waiting: false,
  },
  {
    name: 'Funke A.',
    initials: 'FA',
    msg: 'I want to return this item, the size is wrong',
    channelIcon: <InstagramIcon />,
    channel: 'Instagram',
    time: '8m ago',
    type: 'human',
    waiting: true,
  },
  {
    name: 'Chidi E.',
    initials: 'CE',
    msg: 'Do you have this in size 42? I need it by Friday',
    channelIcon: <GlobeIcon />,
    channel: 'Web Chat',
    time: '12m ago',
    type: 'ai',
    waiting: false,
  },
  {
    name: 'Ngozi I.',
    initials: 'NI',
    msg: 'My payment failed but money was deducted',
    channelIcon: <WhatsAppIcon />,
    channel: 'WhatsApp',
    time: '15m ago',
    type: 'human',
    waiting: true,
  },
  {
    name: 'Tolu M.',
    initials: 'TM',
    msg: 'Can I get a bulk discount for 50 units?',
    channelIcon: <InstagramIcon />,
    channel: 'Instagram',
    time: '22m ago',
    type: 'human',
    waiting: true,
  },
];

export const statusConfig: Record<ActivityStatus, { dotClass: string; label: string }> = {
  success: {
    dotClass: 'feed-status-success',
    label: 'Success',
  },
  escalated: {
    dotClass: 'feed-status-escalated',
    label: 'Escalated',
  },
  failed: {
    dotClass: 'feed-status-failed',
    label: 'Failed',
  },
  info: {
    dotClass: 'feed-status-info',
    label: '',
  },
};
