import {
  SparklesIcon, GlobeIcon, RobotIcon, PackageIcon,
  ShoppingBagIcon, WebhookIcon, CreditCardIcon, SearchIcon,
  ChatIcon, BoltIcon, BarChartIcon, ClockIcon, SendIcon,
  CartIcon, RefreshIcon,
} from '@/components/icons';

export interface Listing {
  id: string;
  name: string;
  desc: string;
  author: string;
  authorVerified: boolean;
  icon: React.ReactNode;
  category: string;
  rating: number;
  reviews: number;
  installs: number;
  nodes: number;
  channels: string[];
  tags: string[];
  featured: boolean;
}

export const listings: Listing[] = [
  {
    id: 'mp-1',
    name: 'Smart Customer Onboarding',
    desc: 'Welcomes new customers with a personalized AI conversation, collects preferences, and sets up their account automatically.',
    author: 'HanDl Team',
    authorVerified: true,
    icon: <SparklesIcon />,
    category: 'sales',
    rating: 4.9,
    reviews: 128,
    installs: 3420,
    nodes: 8,
    channels: ['WhatsApp', 'Web Chat', 'Telegram'],
    tags: ['onboarding', 'ai', 'welcome'],
    featured: true,
  },
  {
    id: 'mp-2',
    name: 'Multi-Channel Order Tracker',
    desc: 'Tracks orders across carriers and sends real-time status updates to customers on their preferred messaging channel.',
    author: 'ShipFlow',
    authorVerified: true,
    icon: <PackageIcon />,
    category: 'commerce',
    rating: 4.8,
    reviews: 94,
    installs: 2870,
    nodes: 6,
    channels: ['WhatsApp', 'Email', 'SMS'],
    tags: ['tracking', 'orders', 'notifications'],
    featured: true,
  },
  {
    id: 'mp-3',
    name: 'AI FAQ Responder',
    desc: 'Automatically answers frequently asked questions using AI. Falls back to human agents when confidence is low.',
    author: 'SupportBot Labs',
    authorVerified: false,
    icon: <RobotIcon />,
    category: 'support',
    rating: 4.7,
    reviews: 67,
    installs: 1940,
    nodes: 5,
    channels: ['WhatsApp', 'Instagram', 'Web Chat'],
    tags: ['faq', 'ai', 'support'],
    featured: false,
  },
  {
    id: 'mp-4',
    name: 'Stripe Payment Reminder',
    desc: 'Sends scheduled payment reminders via WhatsApp/SMS, generates Stripe payment links, and confirms receipts.',
    author: 'PayFlow',
    authorVerified: true,
    icon: <CreditCardIcon />,
    category: 'commerce',
    rating: 4.6,
    reviews: 52,
    installs: 1560,
    nodes: 7,
    channels: ['WhatsApp', 'SMS', 'Email'],
    tags: ['payments', 'stripe', 'reminders'],
    featured: false,
  },
  {
    id: 'mp-5',
    name: 'Instagram DM Sales Bot',
    desc: 'Responds to Instagram DMs with product recommendations, handles checkout, and routes complex queries to sales reps.',
    author: 'HanDl Team',
    authorVerified: true,
    icon: <ChatIcon />,
    category: 'sales',
    rating: 4.8,
    reviews: 83,
    installs: 2210,
    nodes: 9,
    channels: ['Instagram'],
    tags: ['instagram', 'sales', 'ai'],
    featured: true,
  },
  {
    id: 'mp-6',
    name: 'Webhook → CRM Sync',
    desc: 'Receives webhooks from external tools (Typeform, Calendly, etc.), enriches data, and syncs it to your CRM.',
    author: 'IntegrationHub',
    authorVerified: false,
    icon: <WebhookIcon />,
    category: 'integration',
    rating: 4.5,
    reviews: 31,
    installs: 890,
    nodes: 5,
    channels: ['Webhook'],
    tags: ['webhook', 'crm', 'sync'],
    featured: false,
  },
  {
    id: 'mp-7',
    name: 'Flash Sale Broadcaster',
    desc: 'Broadcasts time-limited promotions to segmented customer lists across multiple channels simultaneously.',
    author: 'MarketGrowth',
    authorVerified: true,
    icon: <SendIcon />,
    category: 'sales',
    rating: 4.4,
    reviews: 45,
    installs: 1120,
    nodes: 6,
    channels: ['WhatsApp', 'SMS', 'Email', 'Telegram'],
    tags: ['broadcast', 'promotions', 'marketing'],
    featured: false,
  },
  {
    id: 'mp-8',
    name: 'Returns & Refund Processor',
    desc: 'AI handles return requests, validates eligibility, creates tickets, and processes refunds with Stripe integration.',
    author: 'SupportBot Labs',
    authorVerified: false,
    icon: <RefreshIcon />,
    category: 'support',
    rating: 4.6,
    reviews: 38,
    installs: 780,
    nodes: 8,
    channels: ['WhatsApp', 'Web Chat', 'Email'],
    tags: ['returns', 'refunds', 'support'],
    featured: false,
  },
  {
    id: 'mp-9',
    name: 'Scheduled Report Generator',
    desc: 'Generates daily/weekly analytics reports and delivers them to your team via WhatsApp or Email on a cron schedule.',
    author: 'DataPulse',
    authorVerified: true,
    icon: <BarChartIcon />,
    category: 'integration',
    rating: 4.3,
    reviews: 22,
    installs: 540,
    nodes: 4,
    channels: ['WhatsApp', 'Email'],
    tags: ['reports', 'analytics', 'scheduled'],
    featured: false,
  },
  {
    id: 'mp-10',
    name: 'Lead Nurture Drip Campaign',
    desc: 'Runs timed drip sequences over days/weeks. AI personalises messages based on lead score and engagement.',
    author: 'HanDl Team',
    authorVerified: true,
    icon: <ClockIcon />,
    category: 'sales',
    rating: 4.7,
    reviews: 61,
    installs: 1680,
    nodes: 10,
    channels: ['WhatsApp', 'Email', 'SMS'],
    tags: ['drip', 'nurture', 'leads'],
    featured: true,
  },
  {
    id: 'mp-11',
    name: 'Inventory Low-Stock Alert',
    desc: 'Monitors your product inventory via webhooks and sends alerts to your team when stock drops below thresholds.',
    author: 'IntegrationHub',
    authorVerified: false,
    icon: <CartIcon />,
    category: 'commerce',
    rating: 4.2,
    reviews: 18,
    installs: 420,
    nodes: 4,
    channels: ['Webhook', 'WhatsApp', 'Email'],
    tags: ['inventory', 'alerts', 'stock'],
    featured: false,
  },
  {
    id: 'mp-12',
    name: 'Multi-Language Support Bot',
    desc: 'Detects customer language automatically, translates messages, and provides AI support in 20+ languages.',
    author: 'GlobalBot',
    authorVerified: true,
    icon: <GlobeIcon />,
    category: 'support',
    rating: 4.8,
    reviews: 76,
    installs: 2040,
    nodes: 7,
    channels: ['WhatsApp', 'Instagram', 'Web Chat', 'Telegram'],
    tags: ['multilingual', 'translation', 'support'],
    featured: true,
  },
];

export const categories = ['All', 'Sales', 'Commerce', 'Support', 'Integration'];
export const sortOptions = ['Popular', 'Highest Rated', 'Newest', 'Most Reviews'];
